# Cloudflare Pages Configuration
name = "convoylife"
compatibility_date = "2024-01-01"

[build]
command = "npm run build"
cwd = "."
watch_dirs = ["src"]

[build.upload]
format = "service-worker"

[[build.upload.rules]]
type = "ESModule"
globs = ["**/*.js"]

